package jp.co.sekisui.batch.base.entity.sk001;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class FiResult991TExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public FiResult991TExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andProcessDateIsNull() {
            addCriterion("\"PROCESS_DATE\" is null");
            return (Criteria) this;
        }

        public Criteria andProcessDateIsNotNull() {
            addCriterion("\"PROCESS_DATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andProcessDateEqualTo(Date value) {
            addCriterionForJDBCDate("\"PROCESS_DATE\" =", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("\"PROCESS_DATE\" <>", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateGreaterThan(Date value) {
            addCriterionForJDBCDate("\"PROCESS_DATE\" >", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"PROCESS_DATE\" >=", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateLessThan(Date value) {
            addCriterionForJDBCDate("\"PROCESS_DATE\" <", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"PROCESS_DATE\" <=", value, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateIn(List<Date> values) {
            addCriterionForJDBCDate("\"PROCESS_DATE\" in", values, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("\"PROCESS_DATE\" not in", values, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"PROCESS_DATE\" between", value1, value2, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"PROCESS_DATE\" not between", value1, value2, "processDate");
            return (Criteria) this;
        }

        public Criteria andProcessTimeIsNull() {
            addCriterion("\"PROCESS_TIME\" is null");
            return (Criteria) this;
        }

        public Criteria andProcessTimeIsNotNull() {
            addCriterion("\"PROCESS_TIME\" is not null");
            return (Criteria) this;
        }

        public Criteria andProcessTimeEqualTo(Date value) {
            addCriterionForJDBCTime("\"PROCESS_TIME\" =", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("\"PROCESS_TIME\" <>", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("\"PROCESS_TIME\" >", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("\"PROCESS_TIME\" >=", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeLessThan(Date value) {
            addCriterionForJDBCTime("\"PROCESS_TIME\" <", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("\"PROCESS_TIME\" <=", value, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeIn(List<Date> values) {
            addCriterionForJDBCTime("\"PROCESS_TIME\" in", values, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("\"PROCESS_TIME\" not in", values, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("\"PROCESS_TIME\" between", value1, value2, "processTime");
            return (Criteria) this;
        }

        public Criteria andProcessTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("\"PROCESS_TIME\" not between", value1, value2, "processTime");
            return (Criteria) this;
        }

        public Criteria andUuidIsNull() {
            addCriterion("\"UUID\" is null");
            return (Criteria) this;
        }

        public Criteria andUuidIsNotNull() {
            addCriterion("\"UUID\" is not null");
            return (Criteria) this;
        }

        public Criteria andUuidEqualTo(String value) {
            addCriterion("\"UUID\" =", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotEqualTo(String value) {
            addCriterion("\"UUID\" <>", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThan(String value) {
            addCriterion("\"UUID\" >", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidGreaterThanOrEqualTo(String value) {
            addCriterion("\"UUID\" >=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThan(String value) {
            addCriterion("\"UUID\" <", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLessThanOrEqualTo(String value) {
            addCriterion("\"UUID\" <=", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidLike(String value) {
            addCriterion("\"UUID\" like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotLike(String value) {
            addCriterion("\"UUID\" not like", value, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidIn(List<String> values) {
            addCriterion("\"UUID\" in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotIn(List<String> values) {
            addCriterion("\"UUID\" not in", values, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidBetween(String value1, String value2) {
            addCriterion("\"UUID\" between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andUuidNotBetween(String value1, String value2) {
            addCriterion("\"UUID\" not between", value1, value2, "uuid");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNull() {
            addCriterion("\"SEQNO\" is null");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNotNull() {
            addCriterion("\"SEQNO\" is not null");
            return (Criteria) this;
        }

        public Criteria andSeqnoEqualTo(Integer value) {
            addCriterion("\"SEQNO\" =", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotEqualTo(Integer value) {
            addCriterion("\"SEQNO\" <>", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThan(Integer value) {
            addCriterion("\"SEQNO\" >", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"SEQNO\" >=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThan(Integer value) {
            addCriterion("\"SEQNO\" <", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThanOrEqualTo(Integer value) {
            addCriterion("\"SEQNO\" <=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoIn(List<Integer> values) {
            addCriterion("\"SEQNO\" in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotIn(List<Integer> values) {
            addCriterion("\"SEQNO\" not in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoBetween(Integer value1, Integer value2) {
            addCriterion("\"SEQNO\" between", value1, value2, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotBetween(Integer value1, Integer value2) {
            addCriterion("\"SEQNO\" not between", value1, value2, "seqno");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNull() {
            addCriterion("\"SUPPLIER\" is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIsNotNull() {
            addCriterion("\"SUPPLIER\" is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierEqualTo(String value) {
            addCriterion("\"SUPPLIER\" =", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotEqualTo(String value) {
            addCriterion("\"SUPPLIER\" <>", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThan(String value) {
            addCriterion("\"SUPPLIER\" >", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierGreaterThanOrEqualTo(String value) {
            addCriterion("\"SUPPLIER\" >=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThan(String value) {
            addCriterion("\"SUPPLIER\" <", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLessThanOrEqualTo(String value) {
            addCriterion("\"SUPPLIER\" <=", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierLike(String value) {
            addCriterion("\"SUPPLIER\" like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotLike(String value) {
            addCriterion("\"SUPPLIER\" not like", value, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierIn(List<String> values) {
            addCriterion("\"SUPPLIER\" in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotIn(List<String> values) {
            addCriterion("\"SUPPLIER\" not in", values, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierBetween(String value1, String value2) {
            addCriterion("\"SUPPLIER\" between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andSupplierNotBetween(String value1, String value2) {
            addCriterion("\"SUPPLIER\" not between", value1, value2, "supplier");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNull() {
            addCriterion("\"COMPANYCODE\" is null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNotNull() {
            addCriterion("\"COMPANYCODE\" is not null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeEqualTo(String value) {
            addCriterion("\"COMPANYCODE\" =", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotEqualTo(String value) {
            addCriterion("\"COMPANYCODE\" <>", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThan(String value) {
            addCriterion("\"COMPANYCODE\" >", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThanOrEqualTo(String value) {
            addCriterion("\"COMPANYCODE\" >=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThan(String value) {
            addCriterion("\"COMPANYCODE\" <", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThanOrEqualTo(String value) {
            addCriterion("\"COMPANYCODE\" <=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLike(String value) {
            addCriterion("\"COMPANYCODE\" like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotLike(String value) {
            addCriterion("\"COMPANYCODE\" not like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIn(List<String> values) {
            addCriterion("\"COMPANYCODE\" in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotIn(List<String> values) {
            addCriterion("\"COMPANYCODE\" not in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeBetween(String value1, String value2) {
            addCriterion("\"COMPANYCODE\" between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotBetween(String value1, String value2) {
            addCriterion("\"COMPANYCODE\" not between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andFiscalyearIsNull() {
            addCriterion("\"FISCALYEAR\" is null");
            return (Criteria) this;
        }

        public Criteria andFiscalyearIsNotNull() {
            addCriterion("\"FISCALYEAR\" is not null");
            return (Criteria) this;
        }

        public Criteria andFiscalyearEqualTo(String value) {
            addCriterion("\"FISCALYEAR\" =", value, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andFiscalyearNotEqualTo(String value) {
            addCriterion("\"FISCALYEAR\" <>", value, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andFiscalyearGreaterThan(String value) {
            addCriterion("\"FISCALYEAR\" >", value, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andFiscalyearGreaterThanOrEqualTo(String value) {
            addCriterion("\"FISCALYEAR\" >=", value, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andFiscalyearLessThan(String value) {
            addCriterion("\"FISCALYEAR\" <", value, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andFiscalyearLessThanOrEqualTo(String value) {
            addCriterion("\"FISCALYEAR\" <=", value, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andFiscalyearLike(String value) {
            addCriterion("\"FISCALYEAR\" like", value, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andFiscalyearNotLike(String value) {
            addCriterion("\"FISCALYEAR\" not like", value, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andFiscalyearIn(List<String> values) {
            addCriterion("\"FISCALYEAR\" in", values, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andFiscalyearNotIn(List<String> values) {
            addCriterion("\"FISCALYEAR\" not in", values, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andFiscalyearBetween(String value1, String value2) {
            addCriterion("\"FISCALYEAR\" between", value1, value2, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andFiscalyearNotBetween(String value1, String value2) {
            addCriterion("\"FISCALYEAR\" not between", value1, value2, "fiscalyear");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentIsNull() {
            addCriterion("\"ACCOUNTINGDOCUMENT\" is null");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentIsNotNull() {
            addCriterion("\"ACCOUNTINGDOCUMENT\" is not null");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentEqualTo(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" =", value, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentNotEqualTo(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" <>", value, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentGreaterThan(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" >", value, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentGreaterThanOrEqualTo(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" >=", value, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentLessThan(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" <", value, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentLessThanOrEqualTo(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" <=", value, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentLike(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" like", value, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentNotLike(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" not like", value, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentIn(List<String> values) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" in", values, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentNotIn(List<String> values) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" not in", values, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentBetween(String value1, String value2) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" between", value1, value2, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentNotBetween(String value1, String value2) {
            addCriterion("\"ACCOUNTINGDOCUMENT\" not between", value1, value2, "accountingdocument");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemIsNull() {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" is null");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemIsNotNull() {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" is not null");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemEqualTo(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" =", value, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemNotEqualTo(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" <>", value, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemGreaterThan(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" >", value, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemGreaterThanOrEqualTo(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" >=", value, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemLessThan(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" <", value, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemLessThanOrEqualTo(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" <=", value, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemLike(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" like", value, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemNotLike(String value) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" not like", value, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemIn(List<String> values) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" in", values, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemNotIn(List<String> values) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" not in", values, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemBetween(String value1, String value2) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" between", value1, value2, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andAccountingdocumentitemNotBetween(String value1, String value2) {
            addCriterion("\"ACCOUNTINGDOCUMENTITEM\" not between", value1, value2, "accountingdocumentitem");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeIsNull() {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" is null");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeIsNotNull() {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeEqualTo(String value) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" =", value, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeNotEqualTo(String value) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" <>", value, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeGreaterThan(String value) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" >", value, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeGreaterThanOrEqualTo(String value) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" >=", value, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeLessThan(String value) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" <", value, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeLessThanOrEqualTo(String value) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" <=", value, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeLike(String value) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" like", value, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeNotLike(String value) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" not like", value, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeIn(List<String> values) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" in", values, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeNotIn(List<String> values) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" not in", values, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeBetween(String value1, String value2) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" between", value1, value2, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodBeforeNotBetween(String value1, String value2) {
            addCriterion("\"PAYMENTMETHOD_BEFORE\" not between", value1, value2, "paymentmethodBefore");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterIsNull() {
            addCriterion("\"PAYMENTMETHOD_AFTER\" is null");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterIsNotNull() {
            addCriterion("\"PAYMENTMETHOD_AFTER\" is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterEqualTo(String value) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" =", value, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterNotEqualTo(String value) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" <>", value, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterGreaterThan(String value) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" >", value, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterGreaterThanOrEqualTo(String value) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" >=", value, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterLessThan(String value) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" <", value, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterLessThanOrEqualTo(String value) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" <=", value, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterLike(String value) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" like", value, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterNotLike(String value) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" not like", value, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterIn(List<String> values) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" in", values, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterNotIn(List<String> values) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" not in", values, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterBetween(String value1, String value2) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" between", value1, value2, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andPaymentmethodAfterNotBetween(String value1, String value2) {
            addCriterion("\"PAYMENTMETHOD_AFTER\" not between", value1, value2, "paymentmethodAfter");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeIsNull() {
            addCriterion("\"DUECALCULATIONBASEDATE_BEFORE\" is null");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeIsNotNull() {
            addCriterion("\"DUECALCULATIONBASEDATE_BEFORE\" is not null");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeEqualTo(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_BEFORE\" =", value, "duecalculationbasedateBefore");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeNotEqualTo(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_BEFORE\" <>", value, "duecalculationbasedateBefore");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeGreaterThan(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_BEFORE\" >", value, "duecalculationbasedateBefore");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_BEFORE\" >=", value, "duecalculationbasedateBefore");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeLessThan(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_BEFORE\" <", value, "duecalculationbasedateBefore");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_BEFORE\" <=", value, "duecalculationbasedateBefore");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeIn(List<Date> values) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_BEFORE\" in", values, "duecalculationbasedateBefore");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeNotIn(List<Date> values) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_BEFORE\" not in", values, "duecalculationbasedateBefore");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_BEFORE\" between", value1, value2, "duecalculationbasedateBefore");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateBeforeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_BEFORE\" not between", value1, value2, "duecalculationbasedateBefore");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterIsNull() {
            addCriterion("\"DUECALCULATIONBASEDATE_AFTER\" is null");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterIsNotNull() {
            addCriterion("\"DUECALCULATIONBASEDATE_AFTER\" is not null");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterEqualTo(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_AFTER\" =", value, "duecalculationbasedateAfter");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterNotEqualTo(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_AFTER\" <>", value, "duecalculationbasedateAfter");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterGreaterThan(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_AFTER\" >", value, "duecalculationbasedateAfter");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_AFTER\" >=", value, "duecalculationbasedateAfter");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterLessThan(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_AFTER\" <", value, "duecalculationbasedateAfter");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_AFTER\" <=", value, "duecalculationbasedateAfter");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterIn(List<Date> values) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_AFTER\" in", values, "duecalculationbasedateAfter");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterNotIn(List<Date> values) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_AFTER\" not in", values, "duecalculationbasedateAfter");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_AFTER\" between", value1, value2, "duecalculationbasedateAfter");
            return (Criteria) this;
        }

        public Criteria andDuecalculationbasedateAfterNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"DUECALCULATIONBASEDATE_AFTER\" not between", value1, value2, "duecalculationbasedateAfter");
            return (Criteria) this;
        }

        public Criteria andMessageTypeIsNull() {
            addCriterion("\"MESSAGE_TYPE\" is null");
            return (Criteria) this;
        }

        public Criteria andMessageTypeIsNotNull() {
            addCriterion("\"MESSAGE_TYPE\" is not null");
            return (Criteria) this;
        }

        public Criteria andMessageTypeEqualTo(String value) {
            addCriterion("\"MESSAGE_TYPE\" =", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeNotEqualTo(String value) {
            addCriterion("\"MESSAGE_TYPE\" <>", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeGreaterThan(String value) {
            addCriterion("\"MESSAGE_TYPE\" >", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeGreaterThanOrEqualTo(String value) {
            addCriterion("\"MESSAGE_TYPE\" >=", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeLessThan(String value) {
            addCriterion("\"MESSAGE_TYPE\" <", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeLessThanOrEqualTo(String value) {
            addCriterion("\"MESSAGE_TYPE\" <=", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeLike(String value) {
            addCriterion("\"MESSAGE_TYPE\" like", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeNotLike(String value) {
            addCriterion("\"MESSAGE_TYPE\" not like", value, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeIn(List<String> values) {
            addCriterion("\"MESSAGE_TYPE\" in", values, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeNotIn(List<String> values) {
            addCriterion("\"MESSAGE_TYPE\" not in", values, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeBetween(String value1, String value2) {
            addCriterion("\"MESSAGE_TYPE\" between", value1, value2, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageTypeNotBetween(String value1, String value2) {
            addCriterion("\"MESSAGE_TYPE\" not between", value1, value2, "messageType");
            return (Criteria) this;
        }

        public Criteria andMessageIdIsNull() {
            addCriterion("\"MESSAGE_ID\" is null");
            return (Criteria) this;
        }

        public Criteria andMessageIdIsNotNull() {
            addCriterion("\"MESSAGE_ID\" is not null");
            return (Criteria) this;
        }

        public Criteria andMessageIdEqualTo(String value) {
            addCriterion("\"MESSAGE_ID\" =", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotEqualTo(String value) {
            addCriterion("\"MESSAGE_ID\" <>", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThan(String value) {
            addCriterion("\"MESSAGE_ID\" >", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThanOrEqualTo(String value) {
            addCriterion("\"MESSAGE_ID\" >=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThan(String value) {
            addCriterion("\"MESSAGE_ID\" <", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThanOrEqualTo(String value) {
            addCriterion("\"MESSAGE_ID\" <=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLike(String value) {
            addCriterion("\"MESSAGE_ID\" like", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotLike(String value) {
            addCriterion("\"MESSAGE_ID\" not like", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdIn(List<String> values) {
            addCriterion("\"MESSAGE_ID\" in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotIn(List<String> values) {
            addCriterion("\"MESSAGE_ID\" not in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdBetween(String value1, String value2) {
            addCriterion("\"MESSAGE_ID\" between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotBetween(String value1, String value2) {
            addCriterion("\"MESSAGE_ID\" not between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageNoIsNull() {
            addCriterion("\"MESSAGE_NO\" is null");
            return (Criteria) this;
        }

        public Criteria andMessageNoIsNotNull() {
            addCriterion("\"MESSAGE_NO\" is not null");
            return (Criteria) this;
        }

        public Criteria andMessageNoEqualTo(String value) {
            addCriterion("\"MESSAGE_NO\" =", value, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageNoNotEqualTo(String value) {
            addCriterion("\"MESSAGE_NO\" <>", value, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageNoGreaterThan(String value) {
            addCriterion("\"MESSAGE_NO\" >", value, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageNoGreaterThanOrEqualTo(String value) {
            addCriterion("\"MESSAGE_NO\" >=", value, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageNoLessThan(String value) {
            addCriterion("\"MESSAGE_NO\" <", value, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageNoLessThanOrEqualTo(String value) {
            addCriterion("\"MESSAGE_NO\" <=", value, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageNoLike(String value) {
            addCriterion("\"MESSAGE_NO\" like", value, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageNoNotLike(String value) {
            addCriterion("\"MESSAGE_NO\" not like", value, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageNoIn(List<String> values) {
            addCriterion("\"MESSAGE_NO\" in", values, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageNoNotIn(List<String> values) {
            addCriterion("\"MESSAGE_NO\" not in", values, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageNoBetween(String value1, String value2) {
            addCriterion("\"MESSAGE_NO\" between", value1, value2, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageNoNotBetween(String value1, String value2) {
            addCriterion("\"MESSAGE_NO\" not between", value1, value2, "messageNo");
            return (Criteria) this;
        }

        public Criteria andMessageTextIsNull() {
            addCriterion("\"MESSAGE_TEXT\" is null");
            return (Criteria) this;
        }

        public Criteria andMessageTextIsNotNull() {
            addCriterion("\"MESSAGE_TEXT\" is not null");
            return (Criteria) this;
        }

        public Criteria andMessageTextEqualTo(String value) {
            addCriterion("\"MESSAGE_TEXT\" =", value, "messageText");
            return (Criteria) this;
        }

        public Criteria andMessageTextNotEqualTo(String value) {
            addCriterion("\"MESSAGE_TEXT\" <>", value, "messageText");
            return (Criteria) this;
        }

        public Criteria andMessageTextGreaterThan(String value) {
            addCriterion("\"MESSAGE_TEXT\" >", value, "messageText");
            return (Criteria) this;
        }

        public Criteria andMessageTextGreaterThanOrEqualTo(String value) {
            addCriterion("\"MESSAGE_TEXT\" >=", value, "messageText");
            return (Criteria) this;
        }

        public Criteria andMessageTextLessThan(String value) {
            addCriterion("\"MESSAGE_TEXT\" <", value, "messageText");
            return (Criteria) this;
        }

        public Criteria andMessageTextLessThanOrEqualTo(String value) {
            addCriterion("\"MESSAGE_TEXT\" <=", value, "messageText");
            return (Criteria) this;
        }

        public Criteria andMessageTextLike(String value) {
            addCriterion("\"MESSAGE_TEXT\" like", value, "messageText");
            return (Criteria) this;
        }

        public Criteria andMessageTextNotLike(String value) {
            addCriterion("\"MESSAGE_TEXT\" not like", value, "messageText");
            return (Criteria) this;
        }

        public Criteria andMessageTextIn(List<String> values) {
            addCriterion("\"MESSAGE_TEXT\" in", values, "messageText");
            return (Criteria) this;
        }

        public Criteria andMessageTextNotIn(List<String> values) {
            addCriterion("\"MESSAGE_TEXT\" not in", values, "messageText");
            return (Criteria) this;
        }

        public Criteria andMessageTextBetween(String value1, String value2) {
            addCriterion("\"MESSAGE_TEXT\" between", value1, value2, "messageText");
            return (Criteria) this;
        }

        public Criteria andMessageTextNotBetween(String value1, String value2) {
            addCriterion("\"MESSAGE_TEXT\" not between", value1, value2, "messageText");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdIsNull() {
            addCriterion("\"REGIST_USER_ID\" is null");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdIsNotNull() {
            addCriterion("\"REGIST_USER_ID\" is not null");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdEqualTo(String value) {
            addCriterion("\"REGIST_USER_ID\" =", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdNotEqualTo(String value) {
            addCriterion("\"REGIST_USER_ID\" <>", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdGreaterThan(String value) {
            addCriterion("\"REGIST_USER_ID\" >", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("\"REGIST_USER_ID\" >=", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdLessThan(String value) {
            addCriterion("\"REGIST_USER_ID\" <", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdLessThanOrEqualTo(String value) {
            addCriterion("\"REGIST_USER_ID\" <=", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdLike(String value) {
            addCriterion("\"REGIST_USER_ID\" like", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdNotLike(String value) {
            addCriterion("\"REGIST_USER_ID\" not like", value, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdIn(List<String> values) {
            addCriterion("\"REGIST_USER_ID\" in", values, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdNotIn(List<String> values) {
            addCriterion("\"REGIST_USER_ID\" not in", values, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdBetween(String value1, String value2) {
            addCriterion("\"REGIST_USER_ID\" between", value1, value2, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistUserIdNotBetween(String value1, String value2) {
            addCriterion("\"REGIST_USER_ID\" not between", value1, value2, "registUserId");
            return (Criteria) this;
        }

        public Criteria andRegistDateIsNull() {
            addCriterion("\"REGIST_DATE\" is null");
            return (Criteria) this;
        }

        public Criteria andRegistDateIsNotNull() {
            addCriterion("\"REGIST_DATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andRegistDateEqualTo(Date value) {
            addCriterionForJDBCDate("\"REGIST_DATE\" =", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("\"REGIST_DATE\" <>", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateGreaterThan(Date value) {
            addCriterionForJDBCDate("\"REGIST_DATE\" >", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"REGIST_DATE\" >=", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateLessThan(Date value) {
            addCriterionForJDBCDate("\"REGIST_DATE\" <", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"REGIST_DATE\" <=", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateIn(List<Date> values) {
            addCriterionForJDBCDate("\"REGIST_DATE\" in", values, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("\"REGIST_DATE\" not in", values, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"REGIST_DATE\" between", value1, value2, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"REGIST_DATE\" not between", value1, value2, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistTimeIsNull() {
            addCriterion("\"REGIST_TIME\" is null");
            return (Criteria) this;
        }

        public Criteria andRegistTimeIsNotNull() {
            addCriterion("\"REGIST_TIME\" is not null");
            return (Criteria) this;
        }

        public Criteria andRegistTimeEqualTo(Date value) {
            addCriterionForJDBCTime("\"REGIST_TIME\" =", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("\"REGIST_TIME\" <>", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("\"REGIST_TIME\" >", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("\"REGIST_TIME\" >=", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeLessThan(Date value) {
            addCriterionForJDBCTime("\"REGIST_TIME\" <", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("\"REGIST_TIME\" <=", value, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeIn(List<Date> values) {
            addCriterionForJDBCTime("\"REGIST_TIME\" in", values, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("\"REGIST_TIME\" not in", values, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("\"REGIST_TIME\" between", value1, value2, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("\"REGIST_TIME\" not between", value1, value2, "registTime");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampIsNull() {
            addCriterion("\"REGIST_TIMESTAMP\" is null");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampIsNotNull() {
            addCriterion("\"REGIST_TIMESTAMP\" is not null");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampEqualTo(Date value) {
            addCriterion("\"REGIST_TIMESTAMP\" =", value, "registTimestamp");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampNotEqualTo(Date value) {
            addCriterion("\"REGIST_TIMESTAMP\" <>", value, "registTimestamp");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampGreaterThan(Date value) {
            addCriterion("\"REGIST_TIMESTAMP\" >", value, "registTimestamp");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("\"REGIST_TIMESTAMP\" >=", value, "registTimestamp");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampLessThan(Date value) {
            addCriterion("\"REGIST_TIMESTAMP\" <", value, "registTimestamp");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampLessThanOrEqualTo(Date value) {
            addCriterion("\"REGIST_TIMESTAMP\" <=", value, "registTimestamp");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampIn(List<Date> values) {
            addCriterion("\"REGIST_TIMESTAMP\" in", values, "registTimestamp");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampNotIn(List<Date> values) {
            addCriterion("\"REGIST_TIMESTAMP\" not in", values, "registTimestamp");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampBetween(Date value1, Date value2) {
            addCriterion("\"REGIST_TIMESTAMP\" between", value1, value2, "registTimestamp");
            return (Criteria) this;
        }

        public Criteria andRegistTimestampNotBetween(Date value1, Date value2) {
            addCriterion("\"REGIST_TIMESTAMP\" not between", value1, value2, "registTimestamp");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxIsNull() {
            addCriterion("\"REGIST_UUID_UX\" is null");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxIsNotNull() {
            addCriterion("\"REGIST_UUID_UX\" is not null");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxEqualTo(String value) {
            addCriterion("\"REGIST_UUID_UX\" =", value, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxNotEqualTo(String value) {
            addCriterion("\"REGIST_UUID_UX\" <>", value, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxGreaterThan(String value) {
            addCriterion("\"REGIST_UUID_UX\" >", value, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxGreaterThanOrEqualTo(String value) {
            addCriterion("\"REGIST_UUID_UX\" >=", value, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxLessThan(String value) {
            addCriterion("\"REGIST_UUID_UX\" <", value, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxLessThanOrEqualTo(String value) {
            addCriterion("\"REGIST_UUID_UX\" <=", value, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxLike(String value) {
            addCriterion("\"REGIST_UUID_UX\" like", value, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxNotLike(String value) {
            addCriterion("\"REGIST_UUID_UX\" not like", value, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxIn(List<String> values) {
            addCriterion("\"REGIST_UUID_UX\" in", values, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxNotIn(List<String> values) {
            addCriterion("\"REGIST_UUID_UX\" not in", values, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxBetween(String value1, String value2) {
            addCriterion("\"REGIST_UUID_UX\" between", value1, value2, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidUxNotBetween(String value1, String value2) {
            addCriterion("\"REGIST_UUID_UX\" not between", value1, value2, "registUuidUx");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizIsNull() {
            addCriterion("\"REGIST_UUID_BIZ\" is null");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizIsNotNull() {
            addCriterion("\"REGIST_UUID_BIZ\" is not null");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizEqualTo(String value) {
            addCriterion("\"REGIST_UUID_BIZ\" =", value, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizNotEqualTo(String value) {
            addCriterion("\"REGIST_UUID_BIZ\" <>", value, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizGreaterThan(String value) {
            addCriterion("\"REGIST_UUID_BIZ\" >", value, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizGreaterThanOrEqualTo(String value) {
            addCriterion("\"REGIST_UUID_BIZ\" >=", value, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizLessThan(String value) {
            addCriterion("\"REGIST_UUID_BIZ\" <", value, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizLessThanOrEqualTo(String value) {
            addCriterion("\"REGIST_UUID_BIZ\" <=", value, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizLike(String value) {
            addCriterion("\"REGIST_UUID_BIZ\" like", value, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizNotLike(String value) {
            addCriterion("\"REGIST_UUID_BIZ\" not like", value, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizIn(List<String> values) {
            addCriterion("\"REGIST_UUID_BIZ\" in", values, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizNotIn(List<String> values) {
            addCriterion("\"REGIST_UUID_BIZ\" not in", values, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizBetween(String value1, String value2) {
            addCriterion("\"REGIST_UUID_BIZ\" between", value1, value2, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andRegistUuidBizNotBetween(String value1, String value2) {
            addCriterion("\"REGIST_UUID_BIZ\" not between", value1, value2, "registUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("\"UPDATE_USER_ID\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("\"UPDATE_USER_ID\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("\"UPDATE_USER_ID\" =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("\"UPDATE_USER_ID\" <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("\"UPDATE_USER_ID\" >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("\"UPDATE_USER_ID\" >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("\"UPDATE_USER_ID\" <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("\"UPDATE_USER_ID\" <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("\"UPDATE_USER_ID\" like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("\"UPDATE_USER_ID\" not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("\"UPDATE_USER_ID\" in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("\"UPDATE_USER_ID\" not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("\"UPDATE_USER_ID\" between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("\"UPDATE_USER_ID\" not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("\"UPDATE_DATE\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("\"UPDATE_DATE\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterionForJDBCDate("\"UPDATE_DATE\" =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("\"UPDATE_DATE\" <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterionForJDBCDate("\"UPDATE_DATE\" >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"UPDATE_DATE\" >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterionForJDBCDate("\"UPDATE_DATE\" <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"UPDATE_DATE\" <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterionForJDBCDate("\"UPDATE_DATE\" in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("\"UPDATE_DATE\" not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"UPDATE_DATE\" between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"UPDATE_DATE\" not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("\"UPDATE_TIME\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("\"UPDATE_TIME\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterionForJDBCTime("\"UPDATE_TIME\" =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("\"UPDATE_TIME\" <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("\"UPDATE_TIME\" >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("\"UPDATE_TIME\" >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterionForJDBCTime("\"UPDATE_TIME\" <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("\"UPDATE_TIME\" <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterionForJDBCTime("\"UPDATE_TIME\" in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("\"UPDATE_TIME\" not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("\"UPDATE_TIME\" between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("\"UPDATE_TIME\" not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNull() {
            addCriterion("\"UPDATE_TIMESTAMP\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIsNotNull() {
            addCriterion("\"UPDATE_TIMESTAMP\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampEqualTo(Date value) {
            addCriterion("\"UPDATE_TIMESTAMP\" =", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotEqualTo(Date value) {
            addCriterion("\"UPDATE_TIMESTAMP\" <>", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThan(Date value) {
            addCriterion("\"UPDATE_TIMESTAMP\" >", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("\"UPDATE_TIMESTAMP\" >=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThan(Date value) {
            addCriterion("\"UPDATE_TIMESTAMP\" <", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampLessThanOrEqualTo(Date value) {
            addCriterion("\"UPDATE_TIMESTAMP\" <=", value, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampIn(List<Date> values) {
            addCriterion("\"UPDATE_TIMESTAMP\" in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotIn(List<Date> values) {
            addCriterion("\"UPDATE_TIMESTAMP\" not in", values, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampBetween(Date value1, Date value2) {
            addCriterion("\"UPDATE_TIMESTAMP\" between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateTimestampNotBetween(Date value1, Date value2) {
            addCriterion("\"UPDATE_TIMESTAMP\" not between", value1, value2, "updateTimestamp");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxIsNull() {
            addCriterion("\"UPDATE_UUID_UX\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxIsNotNull() {
            addCriterion("\"UPDATE_UUID_UX\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxEqualTo(String value) {
            addCriterion("\"UPDATE_UUID_UX\" =", value, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxNotEqualTo(String value) {
            addCriterion("\"UPDATE_UUID_UX\" <>", value, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxGreaterThan(String value) {
            addCriterion("\"UPDATE_UUID_UX\" >", value, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxGreaterThanOrEqualTo(String value) {
            addCriterion("\"UPDATE_UUID_UX\" >=", value, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxLessThan(String value) {
            addCriterion("\"UPDATE_UUID_UX\" <", value, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxLessThanOrEqualTo(String value) {
            addCriterion("\"UPDATE_UUID_UX\" <=", value, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxLike(String value) {
            addCriterion("\"UPDATE_UUID_UX\" like", value, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxNotLike(String value) {
            addCriterion("\"UPDATE_UUID_UX\" not like", value, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxIn(List<String> values) {
            addCriterion("\"UPDATE_UUID_UX\" in", values, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxNotIn(List<String> values) {
            addCriterion("\"UPDATE_UUID_UX\" not in", values, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxBetween(String value1, String value2) {
            addCriterion("\"UPDATE_UUID_UX\" between", value1, value2, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidUxNotBetween(String value1, String value2) {
            addCriterion("\"UPDATE_UUID_UX\" not between", value1, value2, "updateUuidUx");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizIsNull() {
            addCriterion("\"UPDATE_UUID_BIZ\" is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizIsNotNull() {
            addCriterion("\"UPDATE_UUID_BIZ\" is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizEqualTo(String value) {
            addCriterion("\"UPDATE_UUID_BIZ\" =", value, "updateUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizNotEqualTo(String value) {
            addCriterion("\"UPDATE_UUID_BIZ\" <>", value, "updateUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizGreaterThan(String value) {
            addCriterion("\"UPDATE_UUID_BIZ\" >", value, "updateUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizGreaterThanOrEqualTo(String value) {
            addCriterion("\"UPDATE_UUID_BIZ\" >=", value, "updateUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizLessThan(String value) {
            addCriterion("\"UPDATE_UUID_BIZ\" <", value, "updateUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizLessThanOrEqualTo(String value) {
            addCriterion("\"UPDATE_UUID_BIZ\" <=", value, "updateUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizLike(String value) {
            addCriterion("\"UPDATE_UUID_BIZ\" like", value, "updateUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizNotLike(String value) {
            addCriterion("\"UPDATE_UUID_BIZ\" not like", value, "updateUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizIn(List<String> values) {
            addCriterion("\"UPDATE_UUID_BIZ\" in", values, "updateUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizNotIn(List<String> values) {
            addCriterion("\"UPDATE_UUID_BIZ\" not in", values, "updateUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizBetween(String value1, String value2) {
            addCriterion("\"UPDATE_UUID_BIZ\" between", value1, value2, "updateUuidBiz");
            return (Criteria) this;
        }

        public Criteria andUpdateUuidBizNotBetween(String value1, String value2) {
            addCriterion("\"UPDATE_UUID_BIZ\" not between", value1, value2, "updateUuidBiz");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 17 05:39:08 UTC 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SK001.FI_RESULT_991_T
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}