package jp.co.sekisui.batch.base.entity.sk001;

import java.util.Date;

public class FiResult991T {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.PROCESS_DATE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private Date processDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.PROCESS_TIME
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private Date processTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.UUID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.SEQNO
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private Integer seqno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.SUPPLIER
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String supplier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.COMPANYCODE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String companycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.FISCALYEAR
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String fiscalyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.ACCOUNTINGDOCUMENT
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String accountingdocument;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.ACCOUNTINGDOCUMENTITEM
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String accountingdocumentitem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.PAYMENTMETHOD_BEFORE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String paymentmethodBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.PAYMENTMETHOD_AFTER
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String paymentmethodAfter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.DUECALCULATIONBASEDATE_BEFORE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private Date duecalculationbasedateBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.DUECALCULATIONBASEDATE_AFTER
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private Date duecalculationbasedateAfter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.MESSAGE_TYPE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String messageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.MESSAGE_ID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.MESSAGE_NO
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String messageNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.MESSAGE_TEXT
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String messageText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.REGIST_USER_ID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String registUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.REGIST_DATE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private Date registDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.REGIST_TIME
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private Date registTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.REGIST_TIMESTAMP
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private Date registTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.REGIST_UUID_UX
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String registUuidUx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.REGIST_UUID_BIZ
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String registUuidBiz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.UPDATE_USER_ID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.UPDATE_DATE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.UPDATE_TIME
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.UPDATE_TIMESTAMP
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private Date updateTimestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.UPDATE_UUID_UX
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String updateUuidUx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SK001.FI_RESULT_991_T.UPDATE_UUID_BIZ
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    private String updateUuidBiz;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.PROCESS_DATE
     *
     * @return the value of SK001.FI_RESULT_991_T.PROCESS_DATE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Date getProcessDate() {
        return processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.PROCESS_DATE
     *
     * @param processDate the value for SK001.FI_RESULT_991_T.PROCESS_DATE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.PROCESS_TIME
     *
     * @return the value of SK001.FI_RESULT_991_T.PROCESS_TIME
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Date getProcessTime() {
        return processTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.PROCESS_TIME
     *
     * @param processTime the value for SK001.FI_RESULT_991_T.PROCESS_TIME
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setProcessTime(Date processTime) {
        this.processTime = processTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.UUID
     *
     * @return the value of SK001.FI_RESULT_991_T.UUID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.UUID
     *
     * @param uuid the value for SK001.FI_RESULT_991_T.UUID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.SEQNO
     *
     * @return the value of SK001.FI_RESULT_991_T.SEQNO
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Integer getSeqno() {
        return seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.SEQNO
     *
     * @param seqno the value for SK001.FI_RESULT_991_T.SEQNO
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setSeqno(Integer seqno) {
        this.seqno = seqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.SUPPLIER
     *
     * @return the value of SK001.FI_RESULT_991_T.SUPPLIER
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getSupplier() {
        return supplier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.SUPPLIER
     *
     * @param supplier the value for SK001.FI_RESULT_991_T.SUPPLIER
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setSupplier(String supplier) {
        this.supplier = supplier == null ? null : supplier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.COMPANYCODE
     *
     * @return the value of SK001.FI_RESULT_991_T.COMPANYCODE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.COMPANYCODE
     *
     * @param companycode the value for SK001.FI_RESULT_991_T.COMPANYCODE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setCompanycode(String companycode) {
        this.companycode = companycode == null ? null : companycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.FISCALYEAR
     *
     * @return the value of SK001.FI_RESULT_991_T.FISCALYEAR
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getFiscalyear() {
        return fiscalyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.FISCALYEAR
     *
     * @param fiscalyear the value for SK001.FI_RESULT_991_T.FISCALYEAR
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setFiscalyear(String fiscalyear) {
        this.fiscalyear = fiscalyear == null ? null : fiscalyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.ACCOUNTINGDOCUMENT
     *
     * @return the value of SK001.FI_RESULT_991_T.ACCOUNTINGDOCUMENT
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getAccountingdocument() {
        return accountingdocument;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.ACCOUNTINGDOCUMENT
     *
     * @param accountingdocument the value for SK001.FI_RESULT_991_T.ACCOUNTINGDOCUMENT
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setAccountingdocument(String accountingdocument) {
        this.accountingdocument = accountingdocument == null ? null : accountingdocument.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.ACCOUNTINGDOCUMENTITEM
     *
     * @return the value of SK001.FI_RESULT_991_T.ACCOUNTINGDOCUMENTITEM
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getAccountingdocumentitem() {
        return accountingdocumentitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.ACCOUNTINGDOCUMENTITEM
     *
     * @param accountingdocumentitem the value for SK001.FI_RESULT_991_T.ACCOUNTINGDOCUMENTITEM
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setAccountingdocumentitem(String accountingdocumentitem) {
        this.accountingdocumentitem = accountingdocumentitem == null ? null : accountingdocumentitem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.PAYMENTMETHOD_BEFORE
     *
     * @return the value of SK001.FI_RESULT_991_T.PAYMENTMETHOD_BEFORE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getPaymentmethodBefore() {
        return paymentmethodBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.PAYMENTMETHOD_BEFORE
     *
     * @param paymentmethodBefore the value for SK001.FI_RESULT_991_T.PAYMENTMETHOD_BEFORE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setPaymentmethodBefore(String paymentmethodBefore) {
        this.paymentmethodBefore = paymentmethodBefore == null ? null : paymentmethodBefore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.PAYMENTMETHOD_AFTER
     *
     * @return the value of SK001.FI_RESULT_991_T.PAYMENTMETHOD_AFTER
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getPaymentmethodAfter() {
        return paymentmethodAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.PAYMENTMETHOD_AFTER
     *
     * @param paymentmethodAfter the value for SK001.FI_RESULT_991_T.PAYMENTMETHOD_AFTER
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setPaymentmethodAfter(String paymentmethodAfter) {
        this.paymentmethodAfter = paymentmethodAfter == null ? null : paymentmethodAfter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.DUECALCULATIONBASEDATE_BEFORE
     *
     * @return the value of SK001.FI_RESULT_991_T.DUECALCULATIONBASEDATE_BEFORE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Date getDuecalculationbasedateBefore() {
        return duecalculationbasedateBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.DUECALCULATIONBASEDATE_BEFORE
     *
     * @param duecalculationbasedateBefore the value for SK001.FI_RESULT_991_T.DUECALCULATIONBASEDATE_BEFORE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setDuecalculationbasedateBefore(Date duecalculationbasedateBefore) {
        this.duecalculationbasedateBefore = duecalculationbasedateBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.DUECALCULATIONBASEDATE_AFTER
     *
     * @return the value of SK001.FI_RESULT_991_T.DUECALCULATIONBASEDATE_AFTER
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Date getDuecalculationbasedateAfter() {
        return duecalculationbasedateAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.DUECALCULATIONBASEDATE_AFTER
     *
     * @param duecalculationbasedateAfter the value for SK001.FI_RESULT_991_T.DUECALCULATIONBASEDATE_AFTER
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setDuecalculationbasedateAfter(Date duecalculationbasedateAfter) {
        this.duecalculationbasedateAfter = duecalculationbasedateAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.MESSAGE_TYPE
     *
     * @return the value of SK001.FI_RESULT_991_T.MESSAGE_TYPE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getMessageType() {
        return messageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.MESSAGE_TYPE
     *
     * @param messageType the value for SK001.FI_RESULT_991_T.MESSAGE_TYPE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setMessageType(String messageType) {
        this.messageType = messageType == null ? null : messageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.MESSAGE_ID
     *
     * @return the value of SK001.FI_RESULT_991_T.MESSAGE_ID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.MESSAGE_ID
     *
     * @param messageId the value for SK001.FI_RESULT_991_T.MESSAGE_ID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.MESSAGE_NO
     *
     * @return the value of SK001.FI_RESULT_991_T.MESSAGE_NO
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getMessageNo() {
        return messageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.MESSAGE_NO
     *
     * @param messageNo the value for SK001.FI_RESULT_991_T.MESSAGE_NO
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setMessageNo(String messageNo) {
        this.messageNo = messageNo == null ? null : messageNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.MESSAGE_TEXT
     *
     * @return the value of SK001.FI_RESULT_991_T.MESSAGE_TEXT
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getMessageText() {
        return messageText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.MESSAGE_TEXT
     *
     * @param messageText the value for SK001.FI_RESULT_991_T.MESSAGE_TEXT
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setMessageText(String messageText) {
        this.messageText = messageText == null ? null : messageText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.REGIST_USER_ID
     *
     * @return the value of SK001.FI_RESULT_991_T.REGIST_USER_ID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getRegistUserId() {
        return registUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.REGIST_USER_ID
     *
     * @param registUserId the value for SK001.FI_RESULT_991_T.REGIST_USER_ID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setRegistUserId(String registUserId) {
        this.registUserId = registUserId == null ? null : registUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.REGIST_DATE
     *
     * @return the value of SK001.FI_RESULT_991_T.REGIST_DATE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Date getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.REGIST_DATE
     *
     * @param registDate the value for SK001.FI_RESULT_991_T.REGIST_DATE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setRegistDate(Date registDate) {
        this.registDate = registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.REGIST_TIME
     *
     * @return the value of SK001.FI_RESULT_991_T.REGIST_TIME
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Date getRegistTime() {
        return registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.REGIST_TIME
     *
     * @param registTime the value for SK001.FI_RESULT_991_T.REGIST_TIME
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setRegistTime(Date registTime) {
        this.registTime = registTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.REGIST_TIMESTAMP
     *
     * @return the value of SK001.FI_RESULT_991_T.REGIST_TIMESTAMP
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Date getRegistTimestamp() {
        return registTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.REGIST_TIMESTAMP
     *
     * @param registTimestamp the value for SK001.FI_RESULT_991_T.REGIST_TIMESTAMP
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setRegistTimestamp(Date registTimestamp) {
        this.registTimestamp = registTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.REGIST_UUID_UX
     *
     * @return the value of SK001.FI_RESULT_991_T.REGIST_UUID_UX
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getRegistUuidUx() {
        return registUuidUx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.REGIST_UUID_UX
     *
     * @param registUuidUx the value for SK001.FI_RESULT_991_T.REGIST_UUID_UX
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setRegistUuidUx(String registUuidUx) {
        this.registUuidUx = registUuidUx == null ? null : registUuidUx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.REGIST_UUID_BIZ
     *
     * @return the value of SK001.FI_RESULT_991_T.REGIST_UUID_BIZ
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getRegistUuidBiz() {
        return registUuidBiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.REGIST_UUID_BIZ
     *
     * @param registUuidBiz the value for SK001.FI_RESULT_991_T.REGIST_UUID_BIZ
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setRegistUuidBiz(String registUuidBiz) {
        this.registUuidBiz = registUuidBiz == null ? null : registUuidBiz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.UPDATE_USER_ID
     *
     * @return the value of SK001.FI_RESULT_991_T.UPDATE_USER_ID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.UPDATE_USER_ID
     *
     * @param updateUserId the value for SK001.FI_RESULT_991_T.UPDATE_USER_ID
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.UPDATE_DATE
     *
     * @return the value of SK001.FI_RESULT_991_T.UPDATE_DATE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.UPDATE_DATE
     *
     * @param updateDate the value for SK001.FI_RESULT_991_T.UPDATE_DATE
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.UPDATE_TIME
     *
     * @return the value of SK001.FI_RESULT_991_T.UPDATE_TIME
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.UPDATE_TIME
     *
     * @param updateTime the value for SK001.FI_RESULT_991_T.UPDATE_TIME
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.UPDATE_TIMESTAMP
     *
     * @return the value of SK001.FI_RESULT_991_T.UPDATE_TIMESTAMP
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public Date getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.UPDATE_TIMESTAMP
     *
     * @param updateTimestamp the value for SK001.FI_RESULT_991_T.UPDATE_TIMESTAMP
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.UPDATE_UUID_UX
     *
     * @return the value of SK001.FI_RESULT_991_T.UPDATE_UUID_UX
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getUpdateUuidUx() {
        return updateUuidUx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.UPDATE_UUID_UX
     *
     * @param updateUuidUx the value for SK001.FI_RESULT_991_T.UPDATE_UUID_UX
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setUpdateUuidUx(String updateUuidUx) {
        this.updateUuidUx = updateUuidUx == null ? null : updateUuidUx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SK001.FI_RESULT_991_T.UPDATE_UUID_BIZ
     *
     * @return the value of SK001.FI_RESULT_991_T.UPDATE_UUID_BIZ
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public String getUpdateUuidBiz() {
        return updateUuidBiz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SK001.FI_RESULT_991_T.UPDATE_UUID_BIZ
     *
     * @param updateUuidBiz the value for SK001.FI_RESULT_991_T.UPDATE_UUID_BIZ
     *
     * @mbg.generated Mon Jan 17 05:39:08 UTC 2022
     */
    public void setUpdateUuidBiz(String updateUuidBiz) {
        this.updateUuidBiz = updateUuidBiz == null ? null : updateUuidBiz.trim();
    }
}